services:
  angular-video-server:
    image: node:14.15.0 # Use a node version suitable for your Angular app
    container_name: angular-video-server
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Excludes node_modules from being overwritten
    ports:
      - "1991:1991"
    command: bash -c "npm install && npm start"
    restart: always
